### ISSUE TITLE
Can you explain this?

### ISSUE THREAD

**Issue by dijs** [rzimmerman/kal#123]
I am trying to figure out an issue with inline if/otherwise statements...

When you do this:

```
console.log(2 ^ (3 if no otherwise 5))
```

it compiles to this:

```
console.log(Math.pow(2, ((false) ? 3 : 5))); // 32
```

which is what we want, although...

```
console.log 2 ^ (3 if no otherwise 5)
```

compiles to this:

```
console.log((false) ? Math.pow(2, (3)) : 5); // 5
```

which is not the same logic...

Any thoughts on this?

**Comment by rzimmerman** [comment]
Wow good catch. I'm not 100% sure what the difference is here but I'll look into it.

**Comment by rzimmerman** [comment]
@rompetoto this turned out to be an issue with the way Kal was adding implicit parentheses. When it saw the token `if`, it assumed the statement had ended and the rest was a trailing conditional. As a result it added the parenthesis early:

``` kal
console.log 2 ^ (3 if no otherwise 5)
```

turned in to:

``` kal
console.log(2 ^ (3) if no otherwise 5)
```

because it added the end-paren from `console.log` right before the word `if` instead of at the end of the line.

I rewrote the `sugar.litkal` function since it had some other major issues, like not supporting function calls inside of list comprehensions.

**Comment by dijs** [comment]
Nice catch!
