### ISSUE TITLE
No modulo operator

### ISSUE THREAD

**Issue by rzimmerman** [rzimmerman/kal#79]
I'd like statements like:

``` kal
a = 5 mod 2
```

to compile to:

``` javascript
var a = 5 % 2;
```

**Comment by rzimmerman** [comment]
Thanks to @rishib1988 for pointing this out (see gh-78)

**Comment by baldawarishi** [comment]
I get what you're saying. My interest comes in the project because I can use it to teach kids and get them interested. When I was studying, I needed to search what the % operator did (in those days, it was yahoo.com and ask.com) however if you're going that way, any developer would expect plus minus div  divide multiply (negate maybe?) . so some of these will need to be implemented.

I can try my hand at it once I'm done horsing around with other things however this seems a bit complicated, esp since I haven't written a compiler for a decade now.

**Comment by rzimmerman** [comment]
I'm glad you think this is a useful learning tool because that was really part of the desire behind creating it. I really want it to be easy for beginners.

Thanks for pointing out that `mod` was missing. `+`, `-`, `/`, `*`, and `^` (exponent) should all be working so please file a bug if they aren't. I also realized I'm missing bitwise operators, so that's getting fixed soon.

**Comment by rzimmerman** [comment]
@mrshu expressed interest in fixing this

**Comment by rzimmerman** [comment]
I really want to get 0.4.6 out since it has some important fixes, so I'm kicking this forward to 0.4.7.
